name: Run on Push

on:
  workflow_dispatch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    permissions:
      contents: read
      packages: write  # Required for pushing to GHCR
    
    steps:
      - name: run cmd
        run: |
          echo "acrName=TEST" >> "$GITHUB_OUPUT"
          env

